name: Run Pytest on Windows Pull Request to develop

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"
          architecture: "x86"

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -

      - name: Add Poetry to PATH
        run: echo "$env:USERPROFILE\AppData\Roaming\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install dependencies
        run: poetry install --no-root --sync

      - name: Run tests
        run: |
          $env:PYTHONPATH = "src"
          poetry run pytest
